#tomcat
server:
  port: 8004
#  servlet:
#    context-path: /user/login
spring:
  devtools:
    restart:
      enabled: true
    freemarker:
      cache: false
    mvc:
      view:
        prefix: /
        suffix: .html
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: 
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
shiro:
  userNativeSessionManager : true
  # disable URL session rewriting
  sessionManager.sessionIdUrlRewritingEnabled : false
  unauthorizedUrl: /user/login
  web:
    enabled: true
  successUrl: /user/home
#logging:
#  level:
#    root: warn
#    com.Shelf.demo.Controller: debug
#  file:
#    path: D:\boot
#    name: runLog.txt
